blog/urls.py
from django.urls import path

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = 'blog'
urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('blog/<int:pk>', BlogDetailView.as_view(), name='detail'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>', toggle_activity, name='activity'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls'), name='catalog'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import RegisterView, ProfileView, email_verification, UserPasswordResetView, ErrorUserPasswordReset

app_name = 'users'

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('reset-password/', UserPasswordResetView.as_view(), name='reset-password'),
    path('error-reset-password/', ErrorUserPasswordReset.as_view(), name='error-reset-password'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    phone = models.CharField(max_length=30, verbose_name='телефон')
    country = models.CharField(max_length=50, verbose_name='страна')
    avatar = models.ImageField(upload_to="avatar/", verbose_name="аватар", **NULLABLE)

    token = models.CharField(max_length=100, verbose_name='Token', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

        def __str__(self):
            return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User


class UsersRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar')

users/views.py
import secrets

from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetView
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, TemplateView

from users.forms import UsersRegisterForm, UserProfileForm
from users.models import User

from config.settings import EMAIL_HOST_USER


class RegisterView(CreateView):
    model = User
    form_class = UsersRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_mail(
            subject='Подтверждение почты',
            message=f'Перейдите по ссылке для подтверждения почты:{url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordResetView(PasswordResetView):
    template_name = 'users/password_reset_email.html'
    form_class = PasswordResetForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        email = form.cleaned_data['email']
        try:
            user = User.objects.get(email=email)
            if user:
                password = User.objects.make_random_password(
                    length=10,
                    allowed_chars="abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789")
                user.set_password(password)
                user.save()
                send_mail(
                    subject='Сброс пароля',
                    message=f'Ваш новый пароль:{password}',
                    from_email=EMAIL_HOST_USER,
                    recipient_list=[user.email]
                )
                return redirect(reverse('users:login'))
        except:
            return redirect(reverse('users:error-reset-password'))


class ErrorUserPasswordReset(TemplateView):

    template_name = 'users/error_password_reset_email.html'

users/templates/users/error_password_reset_email.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="container">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h5>
                            Пользователь с данной почтой не зарегистрирован.

                        </h5>
                        <h5>
                            Проверьте правильность и <a href="{% url 'users:reset-password' %}">попробуйте заново</a>
                            или <a href="{% url 'users:register' %}">зарегестрируйтесь</a>
                        </h5>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="container">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h5>
                            Вход
                        </h5>
                    </div>
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}

                            <button type="submit" class="btn btn-success">Войти</button>

                        <p><a href="{% url 'users:reset-password' %}">Забыли пароль?</a></p>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/password_reset_email.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="container">
        <form class="row" method="post">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h5>
                            Сброс пароля
                        </h5>
                    </div>
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}

                            <button type="submit" class="btn btn-success">Сбросить</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="container">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h5>
                            Регистрация
                        </h5>
                    </div>
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}

                            <button type="submit" class="btn btn-success">Регистрация</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="container">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h5>
                            Профиль
                        </h5>
                    </div>
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}

                            <button type="submit" class="btn btn-success">Сохранить</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}