blog/urls.py
from django.urls import path

from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = 'blog'
urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('blog/<int:pk>', BlogDetailView.as_view(), name='detail'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>', toggle_activity, name='activity'),

]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import ContactsTemplateView, ProductDetailView, ProductCreateView, ProductListView, \
    ProductUpdateView, ProductDeleteView

app_name = 'product'

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
    path('product/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProductUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls'), name='catalog'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from config import settings

NULLABLE = {"blank": True, "null": True}


class Product(models.Model):
    product_name = models.CharField(max_length=50, verbose_name="Название продукта")
    description = models.TextField(verbose_name="Описание продукта")
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                                verbose_name='Владелец', **NULLABLE)
    product_image = models.ImageField(
        upload_to="products/", verbose_name="Изображение", **NULLABLE
    )
    category = models.ForeignKey(
        'Categories',
        on_delete=models.SET_NULL,
        verbose_name="Категория",
        **NULLABLE,
        related_name="products",
    )
    unit_price = models.FloatField(verbose_name="Цена")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания записи")
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата изменений записи")
    is_active = models.BooleanField(default=False, verbose_name='Признак публикации')

    def __str__(self):
        return f"{self.product_name}({self.description})"

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ["category", "product_name", "unit_price"]
        permissions = [
            ('can_edit_activity', 'Can on/off is_activite'),
            ('can_edit_description', 'Can edit description'),
            ('can_edit_category', 'Can edit category')
        ]


class Categories(models.Model):
    category_name = models.CharField(max_length=50, verbose_name="Название категории")
    description = models.TextField(verbose_name="Описание категории")

    def __str__(self):
        return f"{self.category_name}"

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["category_name"]


class Version(models.Model):
    version_name = models.CharField(max_length=50, verbose_name="Название версии")
    version_number = models.PositiveIntegerField(default=0, verbose_name='Номер версии')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="продукт", **NULLABLE,)
    current_version_indicator = models.BooleanField(default=True, verbose_name='Индикатор текущей версии')

    def __str__(self):
        return f"{self.version_name}"

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"
        ordering = ["version_name"]

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('product_name', 'description', 'product_image', 'category', 'unit_price', 'is_active')

    def clean_product_name(self):
        cleaned_data = self.cleaned_data['product_name']

        if cleaned_data.lower() in ('казино', 'криптовалюта', 'крипта',
            'биржа', 'дешево', 'бесплатно', 'обман',
            'полиция', 'радар'):
            raise forms.ValidationError('Недопустимые слова в названии')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']

        if cleaned_data.lower() in ('казино', 'криптовалюта', 'крипта',
                                    'биржа', 'дешево', 'бесплатно', 'обман',
                                    'полиция', 'радар'):
            raise forms.ValidationError('Недопустимые слова в описании')

        return cleaned_data


class ProductModerForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('description', 'category', 'is_active')


class ProductContentManageForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('is_active',)


class VersionForm(forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy

from catalog.forms import ProductForm, VersionForm, ProductModerForm, ProductContentManageForm
from catalog.models import Product, Version
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView

from catalog.services.services import get_categories_from_cache
from users.models import User


class ProductListView(ListView):
    model = Product

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        for obj in context["object_list"]:
            if Version.objects.filter(product=obj).last():
                obj.active_version = (
                    Version.objects.filter(product=obj, current_version_indicator=True)
                    .last()
                    .version_name
                )
                obj.num_version = (
                    Version.objects.filter(product=obj, current_version_indicator=True)
                    .last()
                    .version_number
                )
                obj.save()

        context['categories'] = get_categories_from_cache()

        return context


class ContactsTemplateView(TemplateView):
    template_name = "catalog/contacts.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Контакты"
        return context

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            name = request.POST.get("name")
            phone = request.POST.get("phone")
            message = request.POST.get("message")
            print(f"{name[0]}({phone[0]}):{message}")
        return HttpResponseRedirect("/contacts")


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    login_url = "users:login"


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("product:list")
    login_url = "users:login"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == "POST":
            context_data["formset"] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data["formset"] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()["formset"]
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.creator = self.request.user
            self.object.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("product:list")
    login_url = "users:login"
    perms = ('catalog.can_edit_activity', 'catalog.can_edit_description', 'catalog.can_edit_category')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == "POST":
            context_data["formset"] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data["formset"] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()["formset"]
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user
        if user == self.object.creator or user.is_superuser:
            return ProductForm
        if user.has_perms(perm_list=self.perms):
            return ProductModerForm
        if user.has_perm('catalog.can_edit_activity'):
            return ProductContentManageForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy("product:list")
    login_url = "users:login"

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>

{% include 'catalog/includes/inc_menu.html' %}
{% block content %}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2024</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>РОССИЯ</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>4027008974</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Калуга, улица Степана Разина 22/48, 248-023</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Введите сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        {% for product in products %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <img src="{{ product.product_image | media_filter }}">
                <div class="card-header">
                    <h2 class="my-0 font-weight-normal">{{ product.product_name }}</h2>
                </div>
                <div class="card-body">
                    <h4 class="card-title pricing-card-title">{{ product.unit_price | floatformat:0 }} ₽</h4>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ product.description | truncatechars:100}}</li>

                    </ul>
                    <a class="btn btn-primary" href="{% url 'product_detail' product.pk %}" role="button">Перейти</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить «{{ object.product_name }}»?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'product:list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        </div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <img src="{{ object.product_image | media_filter }}">
                <div class="card-header">
                    <h2 class="my-0 font-weight-normal">{{ object.product_name }}</h2>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ object.description }}</li>
                    </ul>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <strong>Категория: {{ object.category }}</strong>
                    </ul>
                    <h4 class="card-title pricing-card-title">Цена: {{ object.unit_price }} ₽</h4>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h5>
                            Продукт
                        </h5>
                    </div>
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form|crispy }}

                            <button type="submit" class="btn btn-success">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}


                            </button>
                    </div>
                </div>
            </div>
            {% if user.is_superuser or user == product.creator%}
             <div class="col-6">
                    <div class="card">
                         <div class="card-header">
                        <h5>
                            Версия
                        </h5>
                    </div>
                        <div class="card-body">
                            {{ formset.management_form }}
                            {% for form in formset.forms %}
                                {{ form|crispy }}
                            {% endfor %}
                        </div>
                    </div>

                </div>
            {% endif %}
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container">
    <div class="col-12 mb-3">
        <a class="btn btn-outline-primary" href= "{% url 'product:create' %}" >Создать Продукт</a>
    </div>
    <div class="row text-center">
        {% for product in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <img src="{{ product.product_image | media_filter }}">
                <div class="card-header">
                    <h2 class="my-0 font-weight-normal">{{ product.product_name }}</h2>
                </div>
                <div class="card-body">
                    <h4 class="card-title pricing-card-title">{{ product.unit_price | floatformat:0 }} ₽</h4>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>{{ product.description | truncatechars:100}}</li>
                        <ul class="list-group list-group-flush">
                        {% if product.active_version %}
                            <li class="list-group-item h6">Версия: {{ product.active_version }}</li>
                            <li class="list-group-item h6">Номер версии: {{ product.num_version }}</li>
                        {% endif %}
                        {% if product.creator %}
                            <li class="list-group-item h6">Создатель: {{ product.creator }}</li>
                        {% endif %}
                        </ul>
                    </ul>
                    <a class="btn btn-primary" href="{% url 'product:product_detail' product.pk %}" role="button">Перейти</a>
                    {% if perms.catalog.can_edit_activity and perms.catalog.can_edit_description and perms.catalog.can_edit_category or user == product.creator or user.is_superuser or perms.catalog.can_edit_activity %}
                    <a class="btn btn-primary" href="{% url 'product:update' product.pk %}" role="button">Изменить</a>
                    {% endif %}
                    {% if user.is_superuser or user == product.creator%}
                    <a class="btn btn-primary" href="{% url 'product:delete' product.pk %}" role="button">Удалить</a>
                    {% endif %}

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}